//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBSWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        public int fldMemberId { get; set; }
        public string fldFName { get; set; }
        public string fldLName { get; set; }
        public string fldEmail { get; set; }
        public System.DateTime fldDob { get; set; }
        public string fldGender { get; set; }
        public Nullable<System.DateTime> fldJoinDate { get; set; }
        public string fldHometown { get; set; }
        public string fldCurrentLocation { get; set; }
        public string fldPassword { get; set; }
        public string fldRelationshipStatus { get; set; }
        public Nullable<int> fldActive { get; set; }
    }
}
