//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBSWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int fldStudentID { get; set; }
        public string fldStudentName { get; set; }
        public string fldStudentSSN { get; set; }
        public string fldStudentEmail { get; set; }
        public string fldStudentPhone { get; set; }
        public string fldXMLData { get; set; }
    }
}
